services:

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: weather_app
      MARIADB_USER: student
      MARIADB_PASSWORD: Pass@123
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/weather_app
      DB_USERNAME: student
      DB_PASSWORD: Pass@123

      REDIS_HOST: redis
      REDIS_PORT: 6379

      JWT_SECRET: ${JWT_SECRET}
      WEATHER_API_KEY: ${WEATHER_API_KEY}

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mariadb_data:
